general:
  name: Test_v1
  root_dir: null
  
dset:
  prior_sampler:
    cls: SubpriorParametricSampler
    kwargs:
      param_ranges:
        d_sig:                [8, 12]
        width_sigmas:         [0.5, 3.0]
        k:                    [0.2, 0.7]
        d_A:                  [10, 25]
        d_B:                  [40, 60]
        d_C:                  [20, 30]
        s_A:                  [0.5, 10.0]
        s_B:                  [0.1, 30.0]
        s_C:                  [4.0, 18.0]
        sld_A:                [5.0, 20.0]
        sld_B:                [60.0, 80.0]
        sld_C:                [25.0, 50.0]
        d_sio2:               [50.0, 90.0]
        s_sio2:               [0.1, 6.0] 
        s_si:                 [0.1, 12.0] 
        sld_sio2:               [12.0, 14.0]
        sld_si:                 [20.5, 23.0]
      bound_width_ranges:
        d_sig:                [8, 12]
        width_sigmas:         [0.5, 3.0]
        k:                    [0.2, 0.7]
        d_A:                  [10, 25]
        d_B:                  [40, 60]
        d_C:                  [20, 30]
        s_A:                  [0.5, 10.0]
        s_B:                  [0.1, 30.0]
        s_C:                  [4.0, 18.0]
        sld_A:                [5.0, 20.0]
        sld_B:                [60.0, 80.0]
        sld_C:                [25.0, 50.0]
        d_sio2:               [50.0, 90.0]
        s_sio2:               [0.1, 6.0] 
        s_si:                 [0.1, 12.0]
        sld_sio2:               [12.0, 14.0]
        sld_si:                 [20.5, 23.0]
      model_name: repeating_multilayer_abc
      max_num_layers: 15
      logdist: false
      scale_params_by_ranges: false
      scaled_range: [-1., 1.]
      device: 'cuda'

  q_generator:
    cls: ConstantQ
    kwargs:
      q: [0.02, 0.5, 256]
      device: 'cuda'

  intensity_noise:
    cls: BasicExpIntensityNoise
    kwargs:
      relative_errors: [0.0, 0.2]
      abs_errors: 0.0
      consistent_rel_err: false
      logdist: false
      apply_shift: true
      shift_range: [-0.3, 0.3]
      apply_scaling: true
      scale_range: [-0.02, 0.02]

  q_noise:
    cls: BasicQNoiseGenerator
    kwargs:
      shift_std: 1.0e-3
      noise_std: [0., 1.0e-3]

  curves_scaler:
    cls: LogAffineCurvesScaler
    kwargs:
      weight: 0.2
      bias: 1.0
      eps: 1.0e-10

model:
  network:
    cls: NetworkWithPriorsConvEmb
    pretrained_name: null
    device: 'cuda'
    kwargs:
      in_channels: 1
      hidden_channels: [32, 64, 128, 256, 512, 1024]
      dim_embedding: 128
      dim_avpool: 1
      embedding_net_activation: 'gelu'
      use_batch_norm: true
      dim_out: 17
      layer_width: 512
      num_blocks: 10
      repeats_per_block: 2
      mlp_activation: 'gelu'
      pretrained_embedding_net: null
      dropout_rate: 0.0
   
training:
  num_iterations: 40000
  batch_size: 4096
  lr: 5.0e-4
  grad_accumulation_steps: 1
  clip_grad_norm_max: null
  train_with_q_input: False
  update_tqdm_freq: 1
  optimizer: AdamW
  trainer_kwargs:
    optim_kwargs:
      betas: [0.9, 0.999]
      weight_decay: 0.0005
  callbacks:
    save_best_model:
      enable: true
      freq: 500
    lr_scheduler:
      cls: StepLR
      kwargs:
        step_size: 600
        gamma: 0.5
  logger:
    use_neptune: false